environments:
  DEV:
    URLS:
      API_HOST_URL: "https://lms-axim-dev.raccoongang.com/"
      privacyPolicy: "https://lms-axim-dev.raccoongang.com/privacy"
      termsOfService: "https://lms-axim-dev.raccoongang.com/tos"
      contactUs: "https://lms-axim-dev.raccoongang.com/contact"
      FEEDBACK_EMAIL_ADDRESS: "devops@raccoongang.com"
    OAUTH_CLIENT_ID: "lpMqiQBU1xfAgtOIPBpxzxn4EpHXi8LpYWnVEacF"
    FIREBASE:
      PROJECT_ID: "openedxmobile-dev"
      APPLICATION_ID: "1:60657986297:android:8a3a36e996a4ce1f581028"
      API_KEY: "AIzaSyCNj9QxB8YQ_Dg0mVamS0-6Gs2G2FOg2k4"
      GCM_SENDER_ID: "60657986297"
  STAGE:
    URLS:
      API_HOST_URL: "https://lms-rg-app-ios-stage.raccoongang.com/"
      privacyPolicy: "https://lms-rg-app-ios-stage.raccoongang.com/privacy"
      termsOfService: "https://lms-rg-app-ios-stage.raccoongang.com/tos"
      contactUs: "https://lms-rg-app-ios-stage.raccoongang.com/contact"
      FEEDBACK_EMAIL_ADDRESS: "devops@raccoongang.com"
    OAUTH_CLIENT_ID: "cu4zgoqjg6dLT7juIT6pEAqQfnVwxeGQrhlXNiRG"
    FIREBASE:
      PROJECT_ID: "openedxmobile-stage"
      APPLICATION_ID: "1:156114692773:android:52e1f8435141fae7187b4c"
      API_KEY: "AIzaSyCcE0NS0Uodi0CQXeENMRWAGyRsSFMOlm4"
      GCM_SENDER_ID: "156114692773"
  PROD:
    URLS:
      API_HOST_URL: "https://lms-client-demo-maple.raccoongang.com/"
      privacyPolicy: "https://lms-client-demo-maple.raccoongang.com/privacy"
      termsOfService: "https://lms-client-demo-maple.raccoongang.com/tos"
      contactUs: "https://lms-client-demo-maple.raccoongang.com/contact"
      FEEDBACK_EMAIL_ADDRESS: "devops@raccoongang.com"
    OAUTH_CLIENT_ID: "kAeXuoGP6i22Ag3tlIUkL08agkO4MlJE8jXp6gjk"
    FIREBASE:
      PROJECT_ID: ""
      APPLICATION_ID: ""
      API_KEY: ""
      GCM_SENDER_ID: ""
platformName: "OpenEdX"
platformFullName: "OpenEdX"