environments:
  DEV:
    URLS:
      API_HOST_URL: "https://lms-rg-app-ios-dev.raccoongang.com/"
      privacyPolicy: "https://lms-rg-app-ios-dev.raccoongang.com/privacy"
      termsOfService: "https://lms-rg-app-ios-dev.raccoongang.com/tos"
      contactUs: "https://lms-rg-app-ios-dev.raccoongang.com/contact"
      FEEDBACK_EMAIL_ADDRESS: "devops@raccoongang.com"
    OAUTH_CLIENT_ID: "bkxRoqQTkdBZ2A83nxETVWxSeR3yvM6Xn81OcY9d"
  STAGE:
    URLS:
      API_HOST_URL: "https://lms-rg-app-ios-stage.raccoongang.com/"
      privacyPolicy: "https://lms-rg-app-ios-stage.raccoongang.com/privacy"
      termsOfService: "https://lms-rg-app-ios-stage.raccoongang.com/tos"
      contactUs: "https://lms-rg-app-ios-stage.raccoongang.com/contact"
      FEEDBACK_EMAIL_ADDRESS: "devops@raccoongang.com"
    OAUTH_CLIENT_ID: "cu4zgoqjg6dLT7juIT6pEAqQfnVwxeGQrhlXNiRG"
  PROD:
    URLS:
      API_HOST_URL: "https://lms-client-demo-maple.raccoongang.com/"
      privacyPolicy: "https://lms-client-demo-maple.raccoongang.com/privacy"
      termsOfService: "https://lms-client-demo-maple.raccoongang.com/tos"
      contactUs: "https://lms-client-demo-maple.raccoongang.com/contact"
      FEEDBACK_EMAIL_ADDRESS: "devops@raccoongang.com"
    OAUTH_CLIENT_ID: "kAeXuoGP6i22Ag3tlIUkL08agkO4MlJE8jXp6gjk"
platformName: "New Open edX"
platformFullName: "New Open edX"