API_HOST_URL: 'http://localhost:8000'
ENVIRONMENT_DISPLAY_NAME: 'Localhost'
FEEDBACK_EMAIL_ADDRESS: 'support@example.com'
OAUTH_CLIENT_ID: 'OAUTH_CLIENT_ID'

AGREEMENT_URLS:
  PRIVACY_POLICY_URL: 'https://example.com/privacy'
  TOS_URL: 'https://example.com/tos'
  CONTACT_US_URL: 'https://example.com/contact'

#Platform names
PLATFORM_NAME: "OpenEdX"
PLATFORM_FULL_NAME: "OpenEdX"
#tokenType enum accepts JWT and BEARER only
TOKEN_TYPE: "JWT"
#feature flag for activating What’s New feature
WHATS_NEW_ENABLED: false
